#!/usr/bin/env bash

# Documents - backup Documents directory
#rsync -av --delete ${HOME}/Documents ${local_path}/Backups

# Music - backup Music directory
#rsync -av --delete ${HOME}/Music ${local_path}/Backups

# Docker - backup docker directories and files, excluding some things you don't need to backup (logs, cache files, etc)
#rsync -av --delete ${HOME}/Docker --exclude cache/ --exclude Logs/ --exclude Scanners/ --exclude Cache/ --exclude Logs/ --exclude localhost/ --exclude Metadata/ --exclude Databases/ --exclude cache/ ${local_path}/Backups

# One off, hidden file/directories
#rsync -av --delete ${HOME}/.config/beets/ ${local_path}/Backups/.config/beets/
#rsync -av --delete ${HOME}/.gitconfig ${local_path}/Backups/.gitconfig
#rsync -av --delete ${HOME}/.ssh/ ${local_path}/Backups/.ssh/
